#!/bin/bash

# Go to root directory
cd ~ || exit

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until `install.sh` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# Install brew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
# Install git
brew install git

# Clone respository
mkdir ~/.config
git clone https://github.com/gabehoban/system-configuration.git ~/.config/system-configuration

# Change git repo from https to SSH
git -C ~/.config/system-configuration remote set-url origin git@github.com:gabehoban/system-configuration.git

# Wait for a little while before continuing
echo "We are now installing the needed packages and setting the desired configuration."

# Run macOS install script
bash ~/.config/system-configuration/bin/settings.sh

# Link dotfiles
bash ~/.config/system-configuration/bin/dotfiles.sh

# Change shell to zsh
chsh -s "$(command -v zsh)"

# Cleanup
echo "Brew cleanup"
brew cleanup

echo "Success! Reboot the machine for the changes to take effect"
